const puppeteer = require("puppeteer");

/**
 * Convert HTML string to a PDF buffer using headless Chromium.
 * Note: We keep this small and predictable; the HTML is generated by our own frontend.
 *
 * Module responsibility:
 * - Receive HTML from the frontend and render it with Chromium into a PDF buffer
 */
async function htmlToPdfBuffer(html) {
  const browser = await puppeteer.launch({
    // Works well on most machines without extra config.
    headless: "new"
  });

  try {
    const page = await browser.newPage();

    // A4 is typical for reports; include background colors for nicer output.
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "14mm", right: "14mm", bottom: "14mm", left: "14mm" }
    });

    return pdf;
  } finally {
    await browser.close();
  }
}

module.exports = { htmlToPdfBuffer };

